title: "hiro-sanの山歩き"

description: >
  わたし、hiro-sanが歩いたり登ったり、泊まったりした山歩きをまとめています。

url: ""
baseurl: "/yama-reco"

lang: ja
timezone: Asia/Tokyo
encoding: utf-8

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

logo: /assets/images/logo.png

# slugは保持するがURL生成には未使用
# permalinkは現状未設定（postsデフォルト）

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# future:
# collections:
#   records:
#   logs:
